### ISSUE TITLE
Popup doesnt show up for tabbed views

### ISSUE THREAD

**Issue by mrwaim** [djett41/ionic-content-banner#2]
Hi,

I was investigating why the popup sometimes didnt show up for me.

It was attaching the popup to the wrong ion-view

I'm using 

var qs = body.querySelector('ion-nav-view[nav-view="active"] ion-view[nav-view="active"] .scroll-content');

instead of 

var qs = body.querySelector('ion-view[nav-view="active"] .scroll-content');

But I dont know if that's general for everyone.

**Comment by djett41** [comment]
@mrwaim You dont need to attach it to any elements, it should attach to the current view's content within the current controller in scope for that view.  See the demo for an example.  Thanks!  If you are still having issues can you throw up a codepen so I can see how you are using it?

**Comment by mrwaim** [comment]
I'm not doing the attach, the library is :) The library is mis-finding the 'current view'. This happens when using a tabbed view. I havent used codepen as an author before - I'll try it out tomorrow - thanks!

**Comment by meneliksteiner** [comment]
I have notice the same problem. Content-banner doesn't show up in a tabbed view. It only works in the first active tab, when switching to another tab it's not working.

**Comment by leob** [comment]
I have exactly the same issue: when there are tabs then it can happen that it's attaching the content banner to the wrong view.

This occurs indeed when the app has a nested structure, e.g. with menus and tabs.
I just upgraded to Ionic 1.1.0 so I thought it was related to that, but it isn't.

In my case, I have a side menu, and one of the menu options opens a page with 3 tabs. Then I click another option in the side menu which opens a page without tabs. On that other page I want to show the content banner.

Now, your code does "querySelector('ion-view[nav-view="active"]'. However using a debugger (Chrome dev tools) I found out that there are TWO views with nav-view="active":
- a view that sits inside the page that I am opening (the page without the tabs)
- and secondly a view that sits in the (now-hidden, cached) pag with the 3 tabs. The "active" tab (now hidden) still has the 'active' atribute, even though it isn't visible.

Now, querySector just picks the first one, which happens to be the wrong one.
I think I have a fix already, is it okay if I send you a pull request?

(it was a little bit tricky to find out which view is really the active one, but I figured out a way to do it,
you'll see it in the PR but if you think you can do it in a better way then it's fine with me of course)

By the way, for the rest, thanks for this cool piece of work, it really gives a nice touch to my app.

**Comment by leob** [comment]
Hi, I've opened a pull request for this issue:

https://github.com/djett41/ionic-content-banner/pull/3

Please have a look.

**Comment by djett41** [comment]
@leob Awesome man thanks alot, just started a new job so i have been busy.  I think I'm having the same view selection issue in my ionic-scroll-sista app, so if this works you are the man!! I'll pull it down this week and test it and if everything is good roll out a new version.

**Comment by leob** [comment]
Hey that's cool, thanks ...

I saw you added a few notes (a few instances of != instead of !== and something about a timeout), you want me to look at those? I can fix the "!=" or you can do it if you want (should have run jshint
because then I would have spotted those).

Glad I could help, thanks for your awesome component.

**Comment by djett41** [comment]
thanks again @leob I made the changes, recompiled a dist test and released 1.0.1 along with another feature.  Thanks!

**Comment by leob** [comment]
Hey cool man, thanks for the quick merge, I can go back to the 'official' version now in my project, glad I could help.
