### ISSUE TITLE
Positioning of the "close" icon

### ISSUE THREAD

**Issue by pliablepixels** [djett41/ionic-content-banner#5]
Hello, first thanks for this library. It is excellent (and thanks to ionic marketplace, using which I discovered this)

In my app, when I display the banner, the text looks great but the "X" is not aligned properly. I suspect its a CSS conflict with something else as when  I tried your demo app in ionic view, it shows up correctly.

I've currently directly edited your JS file and added `style="margin-top:-5px"` along with the button display where you call ng-close() but I'd prefer to do in a better way if you have any other suggestion.

Screenshot: http://imgur.com/KXq0lSV

Here is how I am adding your CSS and JS files
https://github.com/pliablepixels/zmNinja/blob/master/www/index.html

Thanks

**Comment by pliablepixels** [comment]
I've moved the fix to my stylesheet like this, so I am closing this issue.

```
.content-banner .content-banner-close
{
    margin-top:-5px;
}
```

**Comment by djett41** [comment]
cool thanks!
