### ISSUE TITLE
the banner will disappear automatically when switching tabs

### ISSUE THREAD

**Issue by TonyLuo** [djett41/ionic-content-banner#8]
the banner shows up on the first tab page, switch to another tab page and then switch back, the banner disappears automatically without closing it. 
it will be better if we can configure it whether it will  disappears automatically.

**Comment by djett41** [comment]
cancelOnStateChange by default is set to true.  You can set this to false and it wont clear on state change

**Comment by TonyLuo** [comment]
thanks @djett41 , after checking the code, I found that  cancelOnStateChange has been changed to be closeOnStateChange :)
